version: "3"

services:
  users_service:
    container_name: "users"
    build: ./users-service
    volumes:
      - ./database.db:/src/app/database.db
      - ./users-service:/src
    ports:
      - "8001:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000