version: "3"

services:
  app:
    container_name: "fast-api"
    build: ./app
    volumes:
      - ../app:/app/
    ports:
      - "8001:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001