"""added Users table

Revision ID: a70a360392fd
Revises: 
Create Date: 2022-07-23 16:59:36.593693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a70a360392fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('home_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('postcode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_postcode'), 'location', ['postcode'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_location_postcode'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
